### PR TITLE
[package] Don’t use GitHub shorthand.

### PR DESCRIPTION
**Pull request by alloy**
So yeah, this was for whatever reason causing yarn to just install the upstream package.

### CODE REVIEW

**Comment by alloy** [comment]
Bump

**Comment by orta** [comment]
really, weird, I just did this in team-nav and it was fine also - at least the source code was definitely the version I expected - https://github.com/artsy/team-navigator/blob/master/package.json#L68

**Comment by orta** [comment]
but I'm willing to say that this can be ... new software :D

**Comment by alloy** [comment]
¯\_(ツ)_/¯

**Pull request merged**
